package com.BreadIQ.myapp.model

/**
 * Ported from the iOS app's `Models/BreadStyleDef.swift`.
 *
 * A `{low, high}` numeric range — used for hydration/yeast percentage
 * ranges and oven/internal temperature ranges. TypeScript models these as
 * 2-tuples (`[number, number]`) in the original Expo app; Swift tuples
 * aren't `Codable`, so the iOS port used a small named struct instead —
 * kept as a data class here for the same reason (fidelity with the
 * verified-against-source field shape, not because Kotlin needs it).
 */
data class NumericRange(
    val low: Double,
    val high: Double,
)

/**
 * Static baking-parameter catalog entry for one bread style (baguette,
 * artisan, ciabatta, etc.) — ideal/acceptable hydration and yeast ranges,
 * default mixing/proofing/baking guidance, and default formula values used
 * to initialize the calculator when a style is selected.
 *
 * Ground truth (per the iOS port): `BREAD_STYLES` in
 * `breadiq-mobile/app/(tabs)/calculator.tsx` — purely client-side static
 * data, no server-side definition. 12 styles, matching the iOS port's own
 * recount (an earlier roadmap guess said 13).
 *
 * Modeled as a plain value type plus a static catalog, not a persisted
 * entity — bundled, ship-time-constant reference data: never user-edited,
 * never independently queried, no relationships to persist.
 */
data class BreadStyleDef(
    val value: String,
    val label: String,
    val hydrationIdeal: Double,
    val hydrationRange: NumericRange,
    val yeastIdeal: Double,
    val yeastRange: NumericRange,
    val hydrationNote: String,
    val yeastNote: String,
    val defaultShape: String,
    val ovenTempF: NumericRange,
    val internalTempF: NumericRange,
    val crustNote: String,
    val mixingSpeed: String,
    val mixingTime: String,
    val mixingNote: String,
    val hasStretchFold: Boolean,
    val stretchFoldSets: Int,
    val hasDegassing: Boolean,
    val degassingNote: String,
    val defaultFlourBlend: List<FlourBlendEntry>? = null,
    val fatIdeal: Double? = null,
    val fatNote: String? = null,
    val defaultFat: Double? = null,
    val defaultSalt: Double? = null,
    val defaultSugar: String? = null,
    val defaultSugarPct: Double? = null,
    /**
     * Mixing-friction contribution (°F added to dough temp during mixing),
     * used by the eventual `ProofTimeCalculator` port's
     * `estimatedInitialDoughTempF` — `THERMAL_FERMENTATION_ENGINE_SPEC.md`
     * §4 on the iOS side. First-pass calibrated values, subject to
     * real-bake correction (see that spec's own framing).
     */
    val frictionFactorF: Double,
)

object BreadStyleCatalog {
    val all: List<BreadStyleDef> = listOf(
        BreadStyleDef(
            value = "baguette", label = "Baguette",
            hydrationIdeal = 65.0, hydrationRange = NumericRange(low = 63.0, high = 68.0),
            yeastIdeal = 0.6, yeastRange = NumericRange(low = 0.5, high = 0.8),
            hydrationNote = "Traditional baguettes ferment at 63–68%. Lower hydration produces the tight, chewy crumb and blistered crust.",
            yeastNote = "Low yeast (0.5–0.8%) for a long, slow ferment that builds complex flavor.",
            defaultShape = "baguette_15",
            ovenTempF = NumericRange(low = 460.0, high = 480.0), internalTempF = NumericRange(low = 205.0, high = 210.0),
            crustNote = "Start at max oven temp with heavy steam. Score deeply for distinct ears. Target golden-amber with blistered crust.",
            mixingSpeed = "Medium", mixingTime = "8–10 min",
            mixingNote = "Full gluten development in mixer — no stretch and folds needed.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = true,
            degassingNote = "Minimal — gently press out excess gas. Preserve some fermentation bubbles.",
            defaultFat = 0.0, defaultSalt = 2.0, frictionFactorF = 17.0,
        ),
        BreadStyleDef(
            value = "country", label = "Country / Pain de Campagne",
            hydrationIdeal = 71.0, hydrationRange = NumericRange(low = 68.0, high = 74.0),
            yeastIdeal = 0.8, yeastRange = NumericRange(low = 0.7, high = 1.0),
            hydrationNote = "Rustic country loaves range from 68–74%. Higher hydration opens the crumb.",
            yeastNote = "Moderate yeast (0.7–1.0%) suits a 4–6 hour bulk ferment.",
            defaultShape = "batard",
            ovenTempF = NumericRange(low = 440.0, high = 460.0), internalTempF = NumericRange(low = 205.0, high = 210.0),
            crustNote = "Lower temp than pure sourdough — the ash and rye accelerate browning. Target deep mahogany crust.",
            mixingSpeed = "Medium", mixingTime = "8–10 min",
            mixingNote = "Full gluten development. The traditional 3-flour blend adds complexity.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = true,
            degassingNote = "Full degas after bulk, reform into ball, 30-min bench rest before shaping.",
            defaultFlourBlend = listOf(
                FlourBlendEntry(type = "bread", percent = 85.0),
                FlourBlendEntry(type = "whole_wheat", percent = 10.0),
                FlourBlendEntry(type = "rye", percent = 5.0),
            ),
            defaultFat = 0.0, defaultSalt = 2.0, frictionFactorF = 15.0,
        ),
        BreadStyleDef(
            value = "artisan", label = "Artisan / Sourdough Style",
            hydrationIdeal = 75.0, hydrationRange = NumericRange(low = 72.0, high = 78.0),
            yeastIdeal = 0.9, yeastRange = NumericRange(low = 0.7, high = 1.2),
            hydrationNote = "Artisan loaves typically fall at 72–78% hydration for an open, irregular crumb.",
            yeastNote = "0.7–1.2% commercial yeast for a balanced bulk of 4–5 hours.",
            defaultShape = "boule",
            ovenTempF = NumericRange(low = 450.0, high = 475.0), internalTempF = NumericRange(low = 205.0, high = 210.0),
            crustNote = "Thick, hearty crust — Dutch oven or heavy steam essential. Bake covered for first 20 min then uncover.",
            mixingSpeed = "Medium", mixingTime = "10–12 min",
            mixingNote = "Full primary gluten development. Bulk includes 4 sets of stretch-and-fold at equal intervals throughout the bulk fermentation window.",
            hasStretchFold = true, stretchFoldSets = 4, hasDegassing = true,
            degassingNote = "Full degas after bulk, reform into ball, 30-min bench rest, then divide and shape.",
            defaultFat = 0.0, defaultSalt = 2.0, frictionFactorF = 16.0,
        ),
        BreadStyleDef(
            value = "ciabatta", label = "Ciabatta",
            hydrationIdeal = 80.0, hydrationRange = NumericRange(low = 78.0, high = 85.0),
            yeastIdeal = 1.0, yeastRange = NumericRange(low = 0.8, high = 1.2),
            hydrationNote = "Ciabatta runs at 78–85% hydration. This very wet dough creates the large air pockets.",
            yeastNote = "~1.0% yeast, often paired with a poolish for flavor and open crumb.",
            defaultShape = "ciabatta_loaf",
            ovenTempF = NumericRange(low = 450.0, high = 475.0), internalTempF = NumericRange(low = 205.0, high = 210.0),
            crustNote = "Thin, shattered-glass crispness. High heat essential. Heavy steam first 12 min, then vent.",
            mixingSpeed = "Low–Medium", mixingTime = "3–5 min",
            mixingNote = "Short development mix only. Primary development via 4 coil folds during bulk.",
            hasStretchFold = true, stretchFoldSets = 4, hasDegassing = false, degassingNote = "",
            fatIdeal = 3.0, fatNote = "3% olive oil is the ciabatta baseline.",
            defaultFat = 2.0, defaultSalt = 2.0, frictionFactorF = 8.0,
        ),
        BreadStyleDef(
            value = "focaccia", label = "Focaccia",
            hydrationIdeal = 80.0, hydrationRange = NumericRange(low = 75.0, high = 85.0),
            yeastIdeal = 1.5, yeastRange = NumericRange(low = 1.0, high = 2.0),
            hydrationNote = "Focaccia targets 75–85% hydration. 80% is the reliable baseline.",
            yeastNote = "Higher yeast (1.0–2.0%) suits focaccia's same-day or next-morning bake.",
            defaultShape = "focaccia_10x15",
            ovenTempF = NumericRange(low = 425.0, high = 450.0), internalTempF = NumericRange(low = 205.0, high = 210.0),
            crustNote = "Golden, oil-crisped bottom. Add liberal olive oil, sea salt, and toppings after dimpling.",
            mixingSpeed = "Low", mixingTime = "Up to 10 min",
            mixingNote = "Low speed. Scale directly to oiled pan — no shaping. Dimple deeply after final proof.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = false, degassingNote = "",
            fatIdeal = 5.0, fatNote = "3–8% olive oil in the dough. 5% is the balanced baseline.",
            defaultFat = 5.0, defaultSalt = 2.0, frictionFactorF = 10.0,
        ),
        BreadStyleDef(
            value = "pizza_ny", label = "NY / Roman Style Pizza",
            hydrationIdeal = 57.0, hydrationRange = NumericRange(low = 55.0, high = 59.0),
            yeastIdeal = 0.6, yeastRange = NumericRange(low = 0.5, high = 0.7),
            hydrationNote = "NY-style pizza dough runs at 57% — lower hydration for crisp base in a standard home oven.",
            yeastNote = "0.6% instant yeast for same-day proof or overnight cold retard.",
            defaultShape = "pizza_12in_ny",
            ovenTempF = NumericRange(low = 450.0, high = 525.0), internalTempF = NumericRange(low = 0.0, high = 0.0),
            crustNote = "Crispy base with puffy, lightly charred rim. Bake on preheated stone or steel at 450–525°F.",
            mixingSpeed = "Medium", mixingTime = "8–10 min",
            mixingNote = "Mix until smooth and elastic — dough should pass windowpane test.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = false, degassingNote = "",
            defaultFlourBlend = listOf(FlourBlendEntry(type = "bread", percent = 100.0)),
            fatIdeal = 5.0, fatNote = "5% oil adds extensibility, richness, and crust browning.",
            defaultFat = 5.0, defaultSalt = 2.0, defaultSugar = "granulated_sugar", defaultSugarPct = 2.0,
            frictionFactorF = 16.0,
        ),
        BreadStyleDef(
            value = "pizza_neo", label = "Neapolitan Pizza",
            hydrationIdeal = 63.0, hydrationRange = NumericRange(low = 62.0, high = 65.0),
            yeastIdeal = 0.3, yeastRange = NumericRange(low = 0.2, high = 0.4),
            hydrationNote = "Neapolitan dough runs at 62–65% — higher than NY to survive flash heat (700°F+).",
            yeastNote = "0.2–0.4% instant yeast for a slow 24–48h cold ferment. Never rush Neapolitan.",
            defaultShape = "pizza_12in_neo",
            ovenTempF = NumericRange(low = 700.0, high = 950.0), internalTempF = NumericRange(low = 0.0, high = 0.0),
            crustNote = "Soft, pillowy cornicione with leopard-spotting char. Requires 700°F+ oven.",
            mixingSpeed = "Low–Medium", mixingTime = "8–10 min",
            mixingNote = "Patient, full gluten development is essential. No oil, no sugar.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = false, degassingNote = "",
            defaultFlourBlend = listOf(FlourBlendEntry(type = "00", percent = 100.0)),
            defaultFat = 0.0, defaultSalt = 2.0, frictionFactorF = 14.0,
        ),
        BreadStyleDef(
            value = "soft_roll", label = "Soft Roll / Sandwich Roll",
            hydrationIdeal = 63.0, hydrationRange = NumericRange(low = 59.0, high = 68.0),
            yeastIdeal = 1.2, yeastRange = NumericRange(low = 1.0, high = 1.5),
            hydrationNote = "Soft rolls target 62–65% hydration — lower than artisan for a manageable, tender dough.",
            yeastNote = "1.0–1.5% yeast for a moderately fast bulk of 1–1.5 hours.",
            defaultShape = "soft_rolls_15oz",
            ovenTempF = NumericRange(low = 375.0, high = 425.0), internalTempF = NumericRange(low = 200.0, high = 205.0),
            crustNote = "Egg wash for browning. Brush with butter or oil immediately after baking for softness.",
            mixingSpeed = "Medium", mixingTime = "6–8 min",
            mixingNote = "Mix at medium speed 6–8 min until smooth and slightly tacky. Incorporate oil in last 2 min.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = true,
            degassingNote = "Full punch-down after bulk, bench rest 10–15 min before portioning.",
            defaultFlourBlend = listOf(FlourBlendEntry(type = "bread", percent = 100.0)),
            fatIdeal = 6.0, fatNote = "5–8% fat gives soft rolls their tender crumb and pillowy bite.",
            defaultFat = 6.0, defaultSalt = 2.0, defaultSugar = "granulated_sugar", defaultSugarPct = 4.0,
            frictionFactorF = 15.0,
        ),
        BreadStyleDef(
            value = "brioche", label = "Brioche",
            hydrationIdeal = 51.0, hydrationRange = NumericRange(low = 50.0, high = 55.0),
            yeastIdeal = 1.5, yeastRange = NumericRange(low = 1.2, high = 2.0),
            hydrationNote = "Effective hydration ~51% — eggs and milk provide most liquid. BreadIQ auto-calculates free water. Adjust slider to vary richness vs. crumb openness.",
            yeastNote = "1.5% instant yeast. High fat and sugar impede yeast — fermentation runs 1.75× longer than lean doughs.",
            defaultShape = "brioche_loaf_9in",
            ovenTempF = NumericRange(low = 350.0, high = 375.0), internalTempF = NumericRange(low = 190.0, high = 195.0),
            crustNote = "Egg wash before baking for a deep, lacquered crust. Bake at 350–375°F — lower than lean breads because sugar caramelizes fast. Internal temp 190–195°F.",
            mixingSpeed = "Low → Medium", mixingTime = "15–20 min",
            mixingNote = "Develop full gluten BEFORE adding butter. Add cold butter in cubes over 5–8 min at low speed. Dough should clean bowl sides and slap the wall — that's correct texture.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = true,
            degassingNote = "Gentle deflation only — fold 2–3 times. Do NOT punch down. Aggressive handling tears the butter lamination.",
            defaultFlourBlend = listOf(FlourBlendEntry(type = "bread", percent = 100.0)),
            fatIdeal = 0.0,
            fatNote = "Butter is handled separately as an enrichment ingredient. Fat slider hidden for brioche.",
            defaultFat = 0.0, defaultSalt = 2.0, defaultSugar = "granulated_sugar", defaultSugarPct = 10.0,
            frictionFactorF = 22.0,
        ),
        BreadStyleDef(
            value = "bagel", label = "Bagel",
            hydrationIdeal = 56.0, hydrationRange = NumericRange(low = 54.0, high = 58.0),
            yeastIdeal = 1.1, yeastRange = NumericRange(low = 0.8, high = 1.2),
            hydrationNote = "Stiff dough (54–58%). The low water content creates the dense, chewy crumb that defines a great bagel. Do not add water — stiffness is structural.",
            yeastNote = "1.0–1.1% instant yeast. 90-min room-temp bulk, then 12–24 hour cold proof for chew and malty depth.",
            defaultShape = "bagel_std_6pk",
            ovenTempF = NumericRange(low = 425.0, high = 425.0), internalTempF = NumericRange(low = 205.0, high = 210.0),
            crustNote = "Boil in barley malt syrup solution 45–60 sec per side. Top immediately. Bake on preheated stone at 425°F for 15–18 min to deep mahogany.",
            mixingSpeed = "Medium", mixingTime = "10–12 min",
            mixingNote = "Full gluten development in mixer. Stiff dough — no stretch-and-folds. Smooth, stiff, non-sticky.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = true,
            degassingNote = "Gentle degas. Divide, round into tight balls, thumb-hole and stretch. Refrigerate immediately after shaping.",
            defaultFlourBlend = listOf(FlourBlendEntry(type = "bread", percent = 100.0)),
            fatIdeal = 0.0, defaultFat = 0.0, defaultSalt = 2.0,
            defaultSugar = "barley_malt", defaultSugarPct = 2.7, frictionFactorF = 20.0,
        ),
        BreadStyleDef(
            value = "english_muffin", label = "English Muffin",
            hydrationIdeal = 75.0, hydrationRange = NumericRange(low = 72.0, high = 78.0),
            yeastIdeal = 0.6, yeastRange = NumericRange(low = 0.5, high = 0.8),
            hydrationNote = "Effective hydration ~75% from whole milk. BreadIQ auto-calculates free water after milk liquid contribution. Milk creates the chewy crumb with characteristic nooks and crannies.",
            yeastNote = "0.6% instant yeast for a slow, flavor-developing fermentation. Cold proof after bulk is strongly recommended for best nook development.",
            defaultShape = "em_std_12pk",
            ovenTempF = NumericRange(low = 325.0, high = 350.0), internalTempF = NumericRange(low = 0.0, high = 0.0),
            crustNote = "Cook on ungreased griddle at medium-low (325–350°F) for 6–8 min per side. Low heat is critical — center must cook through before the surface over-browns.",
            mixingSpeed = "Low–Medium", mixingTime = "8–10 min",
            mixingNote = "Mix to smooth, slightly tacky dough. Do not over-develop. Dough should pull away from bowl cleanly.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = true,
            degassingNote = "Gentle deflation. Divide, round into balls, place in greased ring molds on semolina-dusted surface.",
            defaultFlourBlend = listOf(FlourBlendEntry(type = "bread", percent = 100.0)),
            fatIdeal = 0.0, fatNote = "Butter is handled separately as an enrichment ingredient. Fat slider hidden for English muffin.",
            defaultFat = 0.0, defaultSalt = 2.0, defaultSugar = "granulated_sugar", defaultSugarPct = 3.8,
            frictionFactorF = 13.0,
        ),
        BreadStyleDef(
            value = "pretzel", label = "Soft Pretzel",
            hydrationIdeal = 55.0, hydrationRange = NumericRange(low = 53.0, high = 58.0),
            yeastIdeal = 1.0, yeastRange = NumericRange(low = 0.8, high = 1.2),
            hydrationNote = "Stiff, lean dough (53–58%) similar to bagels. Low hydration creates a tight, chewy crumb and crisp crust after the alkaline bath.",
            yeastNote = "1.0% instant yeast. 90–120 min bulk at room temp. No cold proof needed — same-day baking is standard.",
            defaultShape = "pretzel_std_6pk",
            ovenTempF = NumericRange(low = 400.0, high = 400.0), internalTempF = NumericRange(low = 190.0, high = 195.0),
            crustNote = "Dip in baking soda bath (70g baking soda per 1000g boiling water) for 30–45 sec per side. Score the arch. Add coarse pretzel salt. Bake 400°F for 10–14 min to deep mahogany. Lye option: 25g food-grade lye per 1000g water — deeper colour and authentic snap.",
            mixingSpeed = "Medium", mixingTime = "8–10 min",
            mixingNote = "Full gluten development. Stiff dough — more force than lean bread doughs. Smooth, elastic, slightly tacky. Develop to windowpane.",
            hasStretchFold = false, stretchFoldSets = 0, hasDegassing = true,
            degassingNote = "Divide and pre-shape into tight balls. Rest 15–20 min uncovered. Shape into ropes and form twist.",
            defaultFlourBlend = listOf(FlourBlendEntry(type = "bread", percent = 100.0)),
            fatIdeal = 0.0, defaultFat = 0.0, defaultSalt = 1.8,
            defaultSugar = "granulated_sugar", defaultSugarPct = 0.8, frictionFactorF = 18.0,
        ),
    )
}
